# -*- coding: utf-8 -*-
"""Student Performance Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zrcrtZr75Kz6T7cq9dJPFdU6wGdY3Oyr
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("student scores.csv")
print(df.head())

df.describe()

df.info()

df.isnull().sum()

#Drop 'Unnamed:0' column
df = df.drop("Unnamed: 0", axis = 1)
print(df.head())

df.head()

#Gender Distribution
plt.figure(figsize= (5,5))
ax = sns.countplot(data = df, x = "Gender")
ax.bar_label(ax.containers[0])
plt.title("Gender ditribution")
plt.show()

#from the above chart we have analyze thar:
#the numbers of females in the data is more than the number of males

gb = df.groupby("ParentEduc").agg({"MathScore":"mean","ReadingScore":"mean","WritingScore":"mean"})
print(gb)

#Relationship between Parent's Education and student's Score
plt.figure(figsize= (4,4))
sns.heatmap(gb , annot = True)
plt.title("Relationship between Parent's Education and student's Score")
plt.show()

#from the above chart we have concluded that the education:
#of the parents have a good effect of students

gb1 = df.groupby("ParentMaritalStatus").agg({"MathScore":"mean","ReadingScore":"mean","WritingScore":"mean"})
print(gb1)

#Relationship between Parent's Marital status and student's Score
plt.figure(figsize= (4,4))
sns.heatmap(gb1 , annot = True)
plt.title("Relationship between Parent's Marital status and student's Score")
plt.show()

#from the above chart we have concluded that their is no\negligible:
# impact on the student score due to their parent's marital status

plt.figure(figsize=(10, 5))
plt.subplot(1, 3, 1)
sns.boxplot(data=df, x="MathScore")
plt.subplot(1, 3, 2)
sns.boxplot(data=df, x="ReadingScore")
plt.subplot(1, 3, 3)
sns.boxplot(data=df, x="WritingScore")
plt.tight_layout()
plt.show()

# Distribution of Ethnic Groups
group_counts = df['EthnicGroup'].value_counts()
plt.figure(figsize=(6, 6))
plt.pie(group_counts, labels=group_counts.index, autopct="%1.2f%%")
plt.title("Distribution of Ethnic Groups")
plt.show()

# Distribution of Ethnic Groups
plt.figure(figsize=(8, 6))
ax = sns.countplot(data=df, x='EthnicGroup', palette="Set2")
ax.bar_label(ax.containers[0])
plt.title("Distribution of Ethnic Groups")
plt.show()